SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

INSERT INTO `latest_news_lang` (`id`, `news_id`, `locale`, `slug`, `name`, `des`, `g_title`, `g_des`) VALUES
('1', '1', 'ar', 'افتتاح-مشروع-كمبوند-فاخر-جديد-في-التجمع-الخامس', 'افتتاح مشروع كمبوند فاخر جديد في التجمع الخامس', 'تفاصيل الخبر: افتتاح مشروع كمبوند فاخر جديد في التجمع الخامس', 'افتتاح مشروع كمبوند فاخر جديد في التجمع الخامس', 'وصف ميتا للخبر: افتتاح مشروع كمبوند فاخر جديد في التجمع الخامس'),
('2', '1', 'en', 'new-luxury-compound-launched-in-new-cairo-fifth-settlement', 'New Luxury Compound Launched in New Cairo – Fifth Settlement', 'Details of the news: New Luxury Compound Launched in New Cairo – Fifth Settlement', 'New Luxury Compound Launched in New Cairo – Fifth Settlement', 'Meta description: New Luxury Compound Launched in New Cairo – Fifth Settlement'),
('3', '2', 'ar', 'زيادة-الإقبال-على-الوحدات-الإدارية-بالتجمع-الخامس', 'زيادة الإقبال على الوحدات الإدارية بالتجمع الخامس', 'تفاصيل الخبر: زيادة الإقبال على الوحدات الإدارية بالتجمع الخامس', 'زيادة الإقبال على الوحدات الإدارية بالتجمع الخامس', 'وصف ميتا للخبر: زيادة الإقبال على الوحدات الإدارية بالتجمع الخامس'),
('4', '2', 'en', 'rising-demand-for-administrative-units-in-fifth-settlement', 'Rising Demand for Administrative Units in Fifth Settlement', 'Details of the news: Rising Demand for Administrative Units in Fifth Settlement', 'Rising Demand for Administrative Units in Fifth Settlement', 'Meta description: Rising Demand for Administrative Units in Fifth Settlement'),
('5', '3', 'ar', 'فرص-استثمارية-واعدة-في-قلب-مدينة-6-أكتوبر', 'فرص استثمارية واعدة في قلب مدينة 6 أكتوبر', 'تفاصيل الخبر: فرص استثمارية واعدة في قلب مدينة 6 أكتوبر', 'فرص استثمارية واعدة في قلب مدينة 6 أكتوبر', 'وصف ميتا للخبر: فرص استثمارية واعدة في قلب مدينة 6 أكتوبر'),
('6', '3', 'en', 'promising-investment-opportunities-in-6th-of-october-city', 'Promising Investment Opportunities in 6th of October City', 'Details of the news: Promising Investment Opportunities in 6th of October City', 'Promising Investment Opportunities in 6th of October City', 'Meta description: Promising Investment Opportunities in 6th of October City'),
('7', '4', 'ar', 'هبوط-أسعار-الأراضي-في-مناطق-محددة-من-أكتوبر', 'هبوط أسعار الأراضي في مناطق محددة من أكتوبر', 'تفاصيل الخبر: هبوط أسعار الأراضي في مناطق محددة من أكتوبر', 'هبوط أسعار الأراضي في مناطق محددة من أكتوبر', 'وصف ميتا للخبر: هبوط أسعار الأراضي في مناطق محددة من أكتوبر'),
('8', '4', 'en', 'land-prices-drop-in-selected-areas-of-october-city', 'Land Prices Drop in Selected Areas of October City', 'Details of the news: Land Prices Drop in Selected Areas of October City', 'Land Prices Drop in Selected Areas of October City', 'Meta description: Land Prices Drop in Selected Areas of October City'),
('9', '5', 'ar', 'إطلاق-مشروع-تجاري-ضخم-على-محور-26-يوليو', 'إطلاق مشروع تجاري ضخم على محور 26 يوليو', 'تفاصيل الخبر: إطلاق مشروع تجاري ضخم على محور 26 يوليو', 'إطلاق مشروع تجاري ضخم على محور 26 يوليو', 'وصف ميتا للخبر: إطلاق مشروع تجاري ضخم على محور 26 يوليو'),
('10', '5', 'en', 'massive-commercial-project-launched-on-july-26th-axis', 'Massive Commercial Project Launched on July 26th Axis', 'Details of the news: Massive Commercial Project Launched on July 26th Axis', 'Massive Commercial Project Launched on July 26th Axis', 'Meta description: Massive Commercial Project Launched on July 26th Axis'),
('11', '6', 'ar', 'نمو-مستمر-في-سوق-الشقق-الفاخرة-بالتجمع-الخامس', 'نمو مستمر في سوق الشقق الفاخرة بالتجمع الخامس', 'تفاصيل الخبر: نمو مستمر في سوق الشقق الفاخرة بالتجمع الخامس', 'نمو مستمر في سوق الشقق الفاخرة بالتجمع الخامس', 'وصف ميتا للخبر: نمو مستمر في سوق الشقق الفاخرة بالتجمع الخامس'),
('12', '6', 'en', 'continuous-growth-in-luxury-apartment-market-in-new-cairo', 'Continuous Growth in Luxury Apartment Market in New Cairo', 'Details of the news: Continuous Growth in Luxury Apartment Market in New Cairo', 'Continuous Growth in Luxury Apartment Market in New Cairo', 'Meta description: Continuous Growth in Luxury Apartment Market in New Cairo'),
('13', '7', 'ar', 'توقعات-بارتفاع-أسعار-العقارات-في-6-أكتوبر-خلال-2025', 'توقعات بارتفاع أسعار العقارات في 6 أكتوبر خلال 2025', 'تفاصيل الخبر: توقعات بارتفاع أسعار العقارات في 6 أكتوبر خلال 2025', 'توقعات بارتفاع أسعار العقارات في 6 أكتوبر خلال 2025', 'وصف ميتا للخبر: توقعات بارتفاع أسعار العقارات في 6 أكتوبر خلال 2025'),
('14', '7', 'en', 'property-prices-in-october-city-expected-to-rise-by-2025', 'Property Prices in October City Expected to Rise by 2025', 'Details of the news: Property Prices in October City Expected to Rise by 2025', 'Property Prices in October City Expected to Rise by 2025', 'Meta description: Property Prices in October City Expected to Rise by 2025'),
('15', '8', 'ar', 'أفضل-الكمبوندات-للاستثمار-العقاري-في-التجمع-الخامس', 'أفضل الكمبوندات للاستثمار العقاري في التجمع الخامس', 'تفاصيل الخبر: أفضل الكمبوندات للاستثمار العقاري في التجمع الخامس', 'أفضل الكمبوندات للاستثمار العقاري في التجمع الخامس', 'وصف ميتا للخبر: أفضل الكمبوندات للاستثمار العقاري في التجمع الخامس'),
('16', '8', 'en', 'top-compounds-for-real-estate-investment-in-fifth-settlement', 'Top Compounds for Real Estate Investment in Fifth Settlement', 'Details of the news: Top Compounds for Real Estate Investment in Fifth Settlement', 'Top Compounds for Real Estate Investment in Fifth Settlement', 'Meta description: Top Compounds for Real Estate Investment in Fifth Settlement'),
('17', '9', 'ar', 'الفرص-الذهبية-لشراء-وحدات-تجارية-في-أكتوبر-الجديدة', 'الفرص الذهبية لشراء وحدات تجارية في أكتوبر الجديدة', 'تفاصيل الخبر: الفرص الذهبية لشراء وحدات تجارية في أكتوبر الجديدة', 'الفرص الذهبية لشراء وحدات تجارية في أكتوبر الجديدة', 'وصف ميتا للخبر: الفرص الذهبية لشراء وحدات تجارية في أكتوبر الجديدة'),
('18', '9', 'en', 'golden-opportunities-for-buying-commercial-units-in-new-october', 'Golden Opportunities for Buying Commercial Units in New October', 'Details of the news: Golden Opportunities for Buying Commercial Units in New October', 'Golden Opportunities for Buying Commercial Units in New October', 'Meta description: Golden Opportunities for Buying Commercial Units in New October'),
('19', '10', 'ar', 'توسعات-عمرانية-جديدة-بالقرب-من-العاصمة-الإدارية', 'توسعات عمرانية جديدة بالقرب من العاصمة الإدارية', 'تفاصيل الخبر: توسعات عمرانية جديدة بالقرب من العاصمة الإدارية', 'توسعات عمرانية جديدة بالقرب من العاصمة الإدارية', 'وصف ميتا للخبر: توسعات عمرانية جديدة بالقرب من العاصمة الإدارية'),
('20', '10', 'en', 'urban-expansion-near-the-new-administrative-capital', 'Urban Expansion Near the New Administrative Capital', 'Details of the news: Urban Expansion Near the New Administrative Capital', 'Urban Expansion Near the New Administrative Capital', 'Meta description: Urban Expansion Near the New Administrative Capital'),
('21', '11', 'ar', 'افتتاح-مول-تجاري-جديد-في-قلب-التجمع-الخامس', 'افتتاح مول تجاري جديد في قلب التجمع الخامس', 'تفاصيل الخبر: افتتاح مول تجاري جديد في قلب التجمع الخامس', 'افتتاح مول تجاري جديد في قلب التجمع الخامس', 'وصف ميتا للخبر: افتتاح مول تجاري جديد في قلب التجمع الخامس'),
('22', '11', 'en', 'new-shopping-mall-opens-in-the-heart-of-fifth-settlement', 'New Shopping Mall Opens in the Heart of Fifth Settlement', 'Details of the news: New Shopping Mall Opens in the Heart of Fifth Settlement', 'New Shopping Mall Opens in the Heart of Fifth Settlement', 'Meta description: New Shopping Mall Opens in the Heart of Fifth Settlement'),
('23', '12', 'ar', 'شراكات-استراتيجية-لتطوير-مشروعات-سكنية-في-6-أكتوبر', 'شراكات استراتيجية لتطوير مشروعات سكنية في 6 أكتوبر', 'تفاصيل الخبر: شراكات استراتيجية لتطوير مشروعات سكنية في 6 أكتوبر', 'شراكات استراتيجية لتطوير مشروعات سكنية في 6 أكتوبر', 'وصف ميتا للخبر: شراكات استراتيجية لتطوير مشروعات سكنية في 6 أكتوبر'),
('24', '12', 'en', 'strategic-partnerships-to-develop-housing-projects-in-october-city', 'Strategic Partnerships to Develop Housing Projects in October City', 'Details of the news: Strategic Partnerships to Develop Housing Projects in October City', 'Strategic Partnerships to Develop Housing Projects in October City', 'Meta description: Strategic Partnerships to Develop Housing Projects in October City');
COMMIT;
