SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

INSERT INTO `latest_news_lang` (`id`, `news_id`, `locale`, `slug`, `name`, `des`, `g_title`, `g_des`) VALUES
('1', '1', 'ar', 'إطلاق-مشروع-سكني-فاخر-جديد-في-القاهرة-الجديدة', 'إطلاق مشروع سكني فاخر جديد في القاهرة الجديدة', 'تفاصيل الخبر: إطلاق مشروع سكني فاخر جديد في القاهرة الجديدة', 'إطلاق مشروع سكني فاخر جديد في القاهرة الجديدة', 'وصف ميتا للخبر: إطلاق مشروع سكني فاخر جديد في القاهرة الجديدة'),
('2', '1', 'en', 'new-luxury-residential-project-launched-in-new-cairo', 'New Luxury Residential Project Launched in New Cairo', 'Details of the news: New Luxury Residential Project Launched in New Cairo', 'New Luxury Residential Project Launched in New Cairo', 'Meta description: New Luxury Residential Project Launched in New Cairo'),
('3', '2', 'ar', 'ارتفاع-الطلب-على-الوحدات-التجارية-في-دبي', 'ارتفاع الطلب على الوحدات التجارية في دبي', 'تفاصيل الخبر: ارتفاع الطلب على الوحدات التجارية في دبي', 'ارتفاع الطلب على الوحدات التجارية في دبي', 'وصف ميتا للخبر: ارتفاع الطلب على الوحدات التجارية في دبي'),
('4', '2', 'en', 'rising-demand-for-commercial-units-in-dubai', 'Rising Demand for Commercial Units in Dubai', 'Details of the news: Rising Demand for Commercial Units in Dubai', 'Rising Demand for Commercial Units in Dubai', 'Meta description: Rising Demand for Commercial Units in Dubai'),
('5', '3', 'ar', 'فرص-استثمارية-عقارية-في-العاصمة-الإدارية', 'فرص استثمارية عقارية في العاصمة الإدارية', 'تفاصيل الخبر: فرص استثمارية عقارية في العاصمة الإدارية', 'فرص استثمارية عقارية في العاصمة الإدارية', 'وصف ميتا للخبر: فرص استثمارية عقارية في العاصمة الإدارية'),
('6', '3', 'en', 'real-estate-investment-opportunities-in-the-new-capital', 'Real Estate Investment Opportunities in the New Capital', 'Details of the news: Real Estate Investment Opportunities in the New Capital', 'Real Estate Investment Opportunities in the New Capital', 'Meta description: Real Estate Investment Opportunities in the New Capital'),
('7', '4', 'ar', 'انخفاض-أسعار-العقارات-في-بعض-مناطق-الرياض', 'انخفاض أسعار العقارات في بعض مناطق الرياض', 'تفاصيل الخبر: انخفاض أسعار العقارات في بعض مناطق الرياض', 'انخفاض أسعار العقارات في بعض مناطق الرياض', 'وصف ميتا للخبر: انخفاض أسعار العقارات في بعض مناطق الرياض'),
('8', '4', 'en', 'property-prices-decline-in-some-areas-of-riyadh', 'Property Prices Decline in Some Areas of Riyadh', 'Details of the news: Property Prices Decline in Some Areas of Riyadh', 'Property Prices Decline in Some Areas of Riyadh', 'Meta description: Property Prices Decline in Some Areas of Riyadh'),
('9', '5', 'ar', 'توقعات-بانتعاش-السوق-العقاري-في-أبوظبي', 'توقعات بانتعاش السوق العقاري في أبوظبي', 'تفاصيل الخبر: توقعات بانتعاش السوق العقاري في أبوظبي', 'توقعات بانتعاش السوق العقاري في أبوظبي', 'وصف ميتا للخبر: توقعات بانتعاش السوق العقاري في أبوظبي'),
('10', '5', 'en', 'real-estate-market-expected-to-recover-in-abu-dhabi', 'Real Estate Market Expected to Recover in Abu Dhabi', 'Details of the news: Real Estate Market Expected to Recover in Abu Dhabi', 'Real Estate Market Expected to Recover in Abu Dhabi', 'Meta description: Real Estate Market Expected to Recover in Abu Dhabi'),
('11', '6', 'ar', 'إطلاق-منصة-رقمية-لشراء-العقارات-في-السعودية', 'إطلاق منصة رقمية لشراء العقارات في السعودية', 'تفاصيل الخبر: إطلاق منصة رقمية لشراء العقارات في السعودية', 'إطلاق منصة رقمية لشراء العقارات في السعودية', 'وصف ميتا للخبر: إطلاق منصة رقمية لشراء العقارات في السعودية'),
('12', '6', 'en', 'new-digital-platform-launched-for-property-buying-in-ksa', 'New Digital Platform Launched for Property Buying in KSA', 'Details of the news: New Digital Platform Launched for Property Buying in KSA', 'New Digital Platform Launched for Property Buying in KSA', 'Meta description: New Digital Platform Launched for Property Buying in KSA'),
('13', '7', 'ar', 'مشروع-منتجع-سياحي-فاخر-يفتتح-قريب-ا-في-الساحل-الشمالي', 'مشروع منتجع سياحي فاخر يفتتح قريبًا في الساحل الشمالي', 'تفاصيل الخبر: مشروع منتجع سياحي فاخر يفتتح قريبًا في الساحل الشمالي', 'مشروع منتجع سياحي فاخر يفتتح قريبًا في الساحل الشمالي', 'وصف ميتا للخبر: مشروع منتجع سياحي فاخر يفتتح قريبًا في الساحل الشمالي'),
('14', '7', 'en', 'luxury-resort-project-to-open-soon-in-north-coast', 'Luxury Resort Project to Open Soon in North Coast', 'Details of the news: Luxury Resort Project to Open Soon in North Coast', 'Luxury Resort Project to Open Soon in North Coast', 'Meta description: Luxury Resort Project to Open Soon in North Coast'),
('15', '8', 'ar', 'نمو-مستمر-في-سوق-العقارات-الفاخرة-بدبي', 'نمو مستمر في سوق العقارات الفاخرة بدبي', 'تفاصيل الخبر: نمو مستمر في سوق العقارات الفاخرة بدبي', 'نمو مستمر في سوق العقارات الفاخرة بدبي', 'وصف ميتا للخبر: نمو مستمر في سوق العقارات الفاخرة بدبي'),
('16', '8', 'en', 'luxury-real-estate-market-continues-to-grow-in-dubai', 'Luxury Real Estate Market Continues to Grow in Dubai', 'Details of the news: Luxury Real Estate Market Continues to Grow in Dubai', 'Luxury Real Estate Market Continues to Grow in Dubai', 'Meta description: Luxury Real Estate Market Continues to Grow in Dubai'),
('17', '9', 'ar', 'أهم-النصائح-قبل-شراء-عقار-للاستثمار', 'أهم النصائح قبل شراء عقار للاستثمار', 'تفاصيل الخبر: أهم النصائح قبل شراء عقار للاستثمار', 'أهم النصائح قبل شراء عقار للاستثمار', 'وصف ميتا للخبر: أهم النصائح قبل شراء عقار للاستثمار'),
('18', '9', 'en', 'top-tips-before-buying-property-for-investment', 'Top Tips Before Buying Property for Investment', 'Details of the news: Top Tips Before Buying Property for Investment', 'Top Tips Before Buying Property for Investment', 'Meta description: Top Tips Before Buying Property for Investment'),
('19', '10', 'ar', 'المناطق-الأكثر-جذب-ا-للمستثمرين-العقاريين-في-2025', 'المناطق الأكثر جذبًا للمستثمرين العقاريين في 2025', 'تفاصيل الخبر: المناطق الأكثر جذبًا للمستثمرين العقاريين في 2025', 'المناطق الأكثر جذبًا للمستثمرين العقاريين في 2025', 'وصف ميتا للخبر: المناطق الأكثر جذبًا للمستثمرين العقاريين في 2025'),
('20', '10', 'en', 'top-locations-attracting-real-estate-investors-in-2025', 'Top Locations Attracting Real Estate Investors in 2025', 'Details of the news: Top Locations Attracting Real Estate Investors in 2025', 'Top Locations Attracting Real Estate Investors in 2025', 'Meta description: Top Locations Attracting Real Estate Investors in 2025'),
('21', '11', 'ar', 'مؤتمر-عقاري-عالمي-ينطلق-الشهر-القادم-في-الرياض', 'مؤتمر عقاري عالمي ينطلق الشهر القادم في الرياض', 'تفاصيل الخبر: مؤتمر عقاري عالمي ينطلق الشهر القادم في الرياض', 'مؤتمر عقاري عالمي ينطلق الشهر القادم في الرياض', 'وصف ميتا للخبر: مؤتمر عقاري عالمي ينطلق الشهر القادم في الرياض'),
('22', '11', 'en', 'global-real-estate-conference-to-launch-next-month-in-riyadh', 'Global Real Estate Conference to Launch Next Month in Riyadh', 'Details of the news: Global Real Estate Conference to Launch Next Month in Riyadh', 'Global Real Estate Conference to Launch Next Month in Riyadh', 'Meta description: Global Real Estate Conference to Launch Next Month in Riyadh'),
('23', '12', 'ar', 'شراكة-جديدة-لتطوير-مشاريع-عقارية-ذكية', 'شراكة جديدة لتطوير مشاريع عقارية ذكية', 'تفاصيل الخبر: شراكة جديدة لتطوير مشاريع عقارية ذكية', 'شراكة جديدة لتطوير مشاريع عقارية ذكية', 'وصف ميتا للخبر: شراكة جديدة لتطوير مشاريع عقارية ذكية'),
('24', '12', 'en', 'new-partnership-to-develop-smart-property-projects', 'New Partnership to Develop Smart Property Projects', 'Details of the news: New Partnership to Develop Smart Property Projects', 'New Partnership to Develop Smart Property Projects', 'Meta description: New Partnership to Develop Smart Property Projects');
COMMIT;
