SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

INSERT INTO `latest_news_lang` (`id`, `news_id`, `locale`, `slug`, `name`, `des`, `g_title`, `g_des`) VALUES
('1', '1', 'ar', 'شركة-مكة-تطلق-ميني-كمبوند-جديد-في-بيت-الوطن-أكتوبر', 'شركة مكة تطلق \"ميني كمبوند\" جديد في بيت الوطن – أكتوبر', '<p>في خطوة مبتكرة وغير مسبوقة، أطلقت <strong>شركة مكة</strong> مشروع &quot;ميني كمبوند&quot; سكني متكامل بأكتوبر. يتميز المشروع بفكر جديد في استغلال المساحات، حيث تم تحويل المساحات المهدرة إلى <strong>مساحات خدمية ذكية</strong> تعزز تجربة السكن للعائلات.</p>

<p>يأتي الكمبوند بموقع مميز في قلب أكتوبر، ويمزج بين <strong>الهدوء السكني</strong> والخدمات المتكاملة، حيث يضم <strong>مسجد، حمام سباحة، جيم، منطقة ألعاب أطفال، واستراحة خاصة بالسكان</strong>. مشروع يجمع بين الراحة، الخصوصية، والموقع المثالي، ليمنحك تجربة سكنية مختلفة تناسب نمط حياتك العصري.</p>
', 'شركة مكة تطلق \"ميني كمبوند\" جديد في بيت الوطن – أكتوبر', 'في خطوة مبتكرة وغير مسبوقة، أطلقت شركة مكة مشروع \"ميني كمبوند\" سكني متكامل بأكتوبر. يتميز المشروع بفكر جديد في استغلال المساحات، حيث تم تحويل المساحات المهدرة إلى مساحات خدمية ذكية تعزز تجربة السكن للعائلات.'),
('2', '1', 'en', 'makkah-real-estate-launches-a-new-mini-compound-in-beit-el-watan-october', 'Makkah Real Estate Launches a New Mini Compound in Beit El Watan – October', '<p>In a pioneering move, <strong>Makkah Real Estate</strong> has launched a fully serviced <strong>mini compound</strong> in the heart of <strong>Beit El Watan .</strong>This project introduces a fresh concept by utilizing previously wasted spaces and transforming them into smart service areas that enhance the living experience for families.</p>

<p>Located in a prime area of October, the compound blends <strong>peaceful residential living</strong> with a full range of amenities, including a <strong>mosque, swimming pool, gym, children&#39;s play area, and a private residents&rsquo; lounge</strong>. It&rsquo;s a new lifestyle model offering privacy, convenience, and smart space planning &mdash; all in one exceptional location.</p>
', 'Makkah Real Estate Launches a New Mini Compound in Beit El Watan – October', 'In a pioneering move, Makkah Real Estate has launched a fully serviced mini compound in the heart of Beit El Watan  .This project introduces a fresh concept by utilizing previously wasted spaces and transforming them into smart service areas that enhance the living experience for families.'),
('3', '2', 'ar', 'شركة-مكة-تفتتح-فرع-ا-جديد-ا-بمدينة-6-أكتوبر-بعد-30-عام-ا-من-النجاح-في-الإسكندرية', 'شركة مكة تفتتح فرعًا جديدًا بمدينة 6 أكتوبر بعد 30 عامًا من النجاح في الإسكندرية', '<p>في خطوة تعكس مسيرتها الطويلة وخبرتها الممتدة لأكثر من <strong>30 عامًا في مدينة الإسكندرية</strong>، أعلنت <strong>شركة مكة</strong> عن افتتاح فرعها الجديد بمدينة <strong>6 أكتوبر</strong>، إيذانًا بمرحلة توسع جديدة نحو مشروعات سكنية مميزة.</p>

<p>وتستمر الشركة في التمسك بقيمها من خلال تقديم <strong>وحدات سكنية عالية القيمة</strong>، مع <strong>استغلال مبتكر للمساحات</strong> لتوفير تجربة سكنية راقية. وقد تم التعاقد بالفعل على عدد من <strong>المشروعات الجديدة المتميزة</strong> التي تعكس توجه الشركة نحو التوسع الذكي والالتزام بالجودة.</p>
', 'شركة مكة تفتتح فرعًا جديدًا بمدينة 6 أكتوبر بعد 30 عامًا من النجاح في الإسكندرية', 'في خطوة تعكس مسيرتها الطويلة وخبرتها الممتدة لأكثر من 30 عامًا في مدينة الإسكندرية، أعلنت شركة مكة عن افتتاح فرعها الجديد بمدينة 6 أكتوبر، إيذانًا بمرحلة توسع جديدة نحو مشروعات سكنية مميزة.'),
('4', '2', 'en', 'makkah-real-estate-expands-to-6th-of-october-city-after-30-years-of-success-in-alexandria', 'Makkah Real Estate Expands to 6th of October City After 30 Years of Success in Alexandria', '<p>After a remarkable journey of over <strong>30 years in Alexandria</strong>, <strong>Makkah Real Estate</strong> proudly announces the opening of its new branch in <strong>6th of October City</strong>, marking a new chapter of strategic growth and expansion.</p>

<p>Staying true to its core values, the company continues to offer <strong>high-value residential units</strong> with <strong>creative space utilization</strong> to deliver an elevated living experience. Several <strong>new and distinctive projects</strong> have already been secured, reflecting Makkah&rsquo;s commitment to innovation, quality, and smart development.</p>
', 'Makkah Real Estate Expands to 6th of October City After 30 Years of Success in Alexandria', 'After a remarkable journey of over 30 years in Alexandria, Makkah Real Estate proudly announces the opening of its new branch in 6th of October City, marking a new chapter of strategic growth and expansion.'),
('5', '3', 'ar', 'تعاون-استراتيجي-بين-شركة-مكة-و-criteria-design-group-لإنشاء-كمبوند-سكني-مستدام', 'تعاون استراتيجي بين شركة مكة و Criteria Design Group لإنشاء كمبوند سكني مستدام', '<p>في إطار سعيها الدائم لتقديم مشروعات عقارية مبتكرة، وقّعت <strong>شركة مكة</strong> اتفاق تعاون مع مكتب التصميم المعماري <strong>Criteria Design Group</strong>، حيث قام <strong>المهندس مصطفى عبداللطيف</strong> &ndash; رئيس مجلس إدارة شركة مكة &ndash; بتوقيع الاتفاق مع <strong>الدكتور هشام هلال</strong>، المعماري المبدع ومؤسس المكتب.</p>

<p>يهدف هذا التعاون إلى إنشاء <strong>كمبوند سكني مستدام</strong> يجمع بين التصميم المعماري العصري والمعايير البيئية، بما يعكس رؤية شركة مكة في تطوير مجتمعات سكنية ذكية ومتكاملة تواكب متطلبات المستقبل.</p>
', 'تعاون استراتيجي بين شركة مكة و Criteria Design Group لإنشاء كمبوند سكني مستدام', 'في إطار سعيها الدائم لتقديم مشروعات عقارية مبتكرة، وقّعت شركة مكة اتفاق تعاون مع مكتب التصميم المعماري Criteria Design Group، حيث قام المهندس مصطفى عبداللطيف – رئيس مجلس إدارة شركة مكة – بتوقيع الاتفاق مع الدكتور هشام هلال، '),
('6', '3', 'en', 'strategic-partnership-between-makkah-real-estate-and-criteria-design-group-to-develop-a-sustainable-residential-compound', 'Strategic Partnership Between Makkah Real Estate and Criteria Design Group to Develop a Sustainable Residential Compound', '<p>As part of its ongoing commitment to innovation in real estate development, <strong>Makkah Real Estate</strong> has signed a strategic partnership with leading architectural firm <strong>Criteria Design Group</strong>. The agreement was signed by <strong>Eng. Mostafa Abd El-Latif</strong>, Chairman of Makkah Real Estate, and <strong>Dr. Hesham Helal</strong>, the visionary architect and founder of the firm.</p>

<p>This collaboration aims to develop a <strong>sustainable residential compound</strong> that blends modern architectural design with eco-conscious standards, reflecting Makkah&rsquo;s vision for building smart, integrated communities designed for the future.</p>
', 'Strategic Partnership Between Makkah Real Estate and Criteria Design Group to Develop a Sustainable Residential Compound', 'As part of its ongoing commitment to innovation in real estate development, Makkah Real Estate has signed a strategic partnership with leading architectural firm Criteria Design Group. The agreement was signed by Eng. Mostafa Abd El-Latif,'),
('7', '4', 'ar', 'قريب-ا-مشروع-جديد-من-شركة-مكة-مستوحى-من-روح-البيوت-العربية-الأصيلة', 'قريبًا: مشروع جديد من شركة مكة مستوحى من روح البيوت العربية الأصيلة', '<p>تستعد <strong>شركة مكة</strong> لإطلاق مشروع سكني مميز مستلهم من <strong>البيوت العربية التقليدية</strong>، حيث تم توظيف تصميم <strong>الرواق الداخلي (Courtyard)</strong> ليشكل القلب النابض للمنزل.</p>

<p>يوفر هذا التصميم <strong>إضاءة طبيعية طوال اليوم</strong>، مع دمج <strong>النباتات والنافورة المائية</strong> في الفراغ الداخلي، ما يمنح إحساسًا بالراحة والسكينة داخل المنزل، دون المساس بعنصر <strong>الخصوصية التامة</strong> التي تميز هذا الطراز المعماري. مشروع يعيد إحياء التراث بأسلوب عصري يلائم الحياة الحديثة.</p>
', 'قريبًا: مشروع جديد من شركة مكة مستوحى من روح البيوت العربية الأصيلة', 'تستعد شركة مكة لإطلاق مشروع سكني مميز مستلهم من البيوت العربية التقليدية، حيث تم توظيف تصميم الرواق الداخلي (Courtyard) ليشكل القلب النابض للمنزل.'),
('8', '4', 'en', 'coming-soon-a-new-project-inspired-by-authentic-arab-homes', 'Coming Soon: A New Project Inspired by Authentic Arab Homes', '<p><strong>Makkah Real Estate</strong> is preparing to launch a unique residential project inspired by the timeless charm of <strong>traditional Arab architecture</strong>. At the heart of the design lies the use of an inner <strong>courtyard (riwaq)</strong>, creating a serene and functional living space.</p>

<p>The courtyard allows for <strong>natural daylight throughout the day</strong>, enhanced by the presence of <strong>greenery and a central water fountain</strong>, offering residents a calming, nature-filled atmosphere. All of this comes with <strong>complete privacy</strong>, blending heritage with modern living in a truly exceptional way.</p>
', 'Coming Soon: A New Project Inspired by Authentic Arab Homes', 'Makkah Real Estate is preparing to launch a unique residential project inspired by the timeless charm of traditional Arab architecture. At the heart of the design lies the use of an inner courtyard (riwaq), creating a serene and functional living space.'),
('9', '5', 'ar', 'شركة-مكة-تطلق-نظام-قسم-بيتك-بنفسك-لتخصيص-تقسيمات-الشقق-حسب-رغبة-العميل', 'شركة مكة تطلق نظام \"قسم بيتك بنفسك\" لتخصيص تقسيمات الشقق حسب رغبة العميل', '<p>أطلقت <strong>شركة مكة العقارية</strong> نظامًا مبتكرًا تحت اسم <strong>&quot;Tailored Home &ndash; قسم بيتك بنفسك&quot;</strong>، يمنح العملاء حرية كاملة في إعادة تصميم وتقسيم المساحات الداخلية لشققهم بما يتناسب مع احتياجاتهم وتفضيلاتهم الشخصية.</p>

<p>سواء كنت تفضل <strong>غرفة معيشة واسعة</strong>، أو <strong>مكتب منزلي</strong>، أو <strong>غرفة إضافية للأطفال</strong>، يمكنك الآن تحديد شكل ومساحة كل ركن في شقتك قبل التنفيذ. هذه المبادرة تأتي ضمن توجه شركة مكة لتقديم <strong>حلول سكنية مرنة، عصرية، ومخصصة</strong> لتناسب أسلوب حياة كل عميل.</p>
', 'شركة مكة تطلق نظام \"قسم بيتك بنفسك\" لتخصيص تقسيمات الشقق حسب رغبة العميل', 'أطلقت شركة مكة العقارية نظامًا مبتكرًا تحت اسم \"Tailored Home – قسم بيتك بنفسك\"، يمنح العملاء حرية كاملة في إعادة تصميم وتقسيم المساحات الداخلية لشققهم بما يتناسب مع احتياجاتهم وتفضيلاتهم الشخصية.'),
('10', '5', 'en', 'makkah-real-estate-launches-tailored-home-design-your-apartment-your-way', 'Makkah Real Estate Launches \"Tailored Home\" – Design Your Apartment Your Way', '<p><strong>Makkah Real Estate</strong> has introduced an innovative system called <strong>&quot;Tailored Home &ndash; Design Your Apartment Your Way&quot;</strong>, offering customers the complete freedom to redesign and customize their apartment layouts based on their unique needs and preferences.</p>

<p>Whether you prefer a <strong>spacious living room</strong>, a <strong>home office</strong>, or an <strong>extra bedroom for the kids</strong>, you can now define the layout and function of every corner in your apartment before construction begins. This initiative reflects Makkah&rsquo;s vision to deliver <strong>flexible, modern, and personalized housing solutions</strong> tailored to each client&#39;s lifestyle.</p>
', 'Makkah Real Estate Launches \"Tailored Home\" – Design Your Apartment Your Way', 'Makkah Real Estate has introduced an innovative system called \"Tailored Home – Design Your Apartment Your Way\", offering customers the complete freedom to redesign and customize their apartment layouts based on their unique needs and preferences.');
COMMIT;
